### ISSUE TITLE
[BUG] Visible version number is outdated; hardcoded?

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/migaku-mpv#13]
The latest version `v0.7.0` still displays `v0.6.1` on the `http://127.0.0.1:2222/` page in the top-right.

I assume this is because it's hardcoded. It'd be nice if it were updated, and auto-updated in future.

**Comment by RicBent** [comment]
Automated with 5994f7c9fbf2688084d232391bd2f7be384da30d
