### ISSUE TITLE
Merge changes from aio-compatibility branch into main

### ISSUE THREAD

**Issue by StayBlueee** [migaku-official/migaku-mpv#16]
This is a big issue, and I am slightly shocked that this was overlooked. The version number was bumped, so it was built from the aio-compatibility branch and released the new version, but the changes from the main branch (mainly #11) weren't pulled in along with it, causing the same issues mentioned in #9.

This will fix a lot of headaches for users trying to use the migaku-mpv script.

**Comment by RicBent** [comment]
Sorry for the delay. Next time I'm even just a few days late, lmk right away!

**Comment by StayBlueee** [comment]
> Sorry for the delay. Next time I'm even just a few days late, lmk right away!

Appreciate it! :)
